.TH "gdal_edit" 1 "Mon Nov 20 2017" "GDAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdal_edit \- Edit in place various information of an existing GDAL dataset\&.
.SH "SYNOPSIS"
.PP
.PP
.nf
gdal_edit [--help-general] [-ro] [-a_srs srs_def] [-a_ullr ulx uly lrx lry]
          [-tr xres yres] [-unsetgt] [-a_nodata value] [-unsetnodata]
          [-unsetstats] [-stats] [-approx_stats]
          [-scale value] [-offset value]
          [-gcp pixel line easting northing [elevation]]*
          [-unsetmd] [-oo NAME=VALUE]* [-mo "META-TAG=VALUE"]*  datasetname
.fi
.PP
.SH "DESCRIPTION"
.PP
The gdal_edit\&.py script can be used to edit in place various information of an existing GDAL dataset (projection, geotransform, nodata, metadata)\&.
.PP
It works only with raster formats that support update access to existing datasets\&.
.PP
CAUTION: depending on the format, older values of the updated information might still be found in the file in a 'ghost' state, even if no longer accessible through the GDAL API\&. This is for example the case of the GTiff format (this is not a exhaustive list)
.PP
.IP "\fB\fB--help-general\fP:\fP" 1c
Gives a brief usage message for the generic GDAL commandline options and exit\&. 
.PP
.IP "\fB\fB-ro\fP:\fP" 1c
(GDAL >= 1\&.11) Open the dataset in read-only\&. Might be useful for drivers refusing to use the dataset in update-mode\&. In which case, updated information will go into PAM \&.aux\&.xml files\&.
.PP
.IP "\fB\fB-a_srs\fP \fIsrs_def\fP:\fP" 1c
.PP
Defines the target coordinate system\&. This coordinate system will be written to the dataset\&. If the empty string or None is specified, then the existing coordinate system will be removed (for TIFF/GeoTIFF, might not be well supported besides that)\&.
.PP
.IP "\fB\fB-a_ullr\fP \fIulx uly lrx lry\fP:\fP" 1c
Assign/override the georeferenced bounds of the dataset\&.
.PP
.IP "\fB\fB-tr\fP xres yres :\fP" 1c
Set target resolution\&. The values must be expressed in georeferenced units\&. Both must be positive values\&.
.PP
.IP "\fB\fB-unsetgt\fP:\fP" 1c
Remove the georeference information\&.
.PP
.IP "\fB\fB-unsetstats\fP:\fP" 1c
(GDAL >= 2\&.0) Remove band statistics information\&.
.PP
.IP "\fB\fB-stats\fP:\fP" 1c
(GDAL >= 2\&.0) Calculate and store band statistics\&.
.PP
.IP "\fB\fB-approx_stats\fP:\fP" 1c
(GDAL >= 2\&.0) Calculate and store approximate band statistics\&.
.PP
.IP "\fB\fB-a_nodata\fP \fIvalue\fP:\fP" 1c
Assign a specified nodata value to output bands\&.
.PP
.IP "\fB\fB-unsetnodata\fP:\fP" 1c
(GDAL >= 2\&.1) Remove existing nodata values\&.
.PP
.IP "\fB\fB-scale\fP \fIvalue\fP:\fP" 1c
(GDAL >= 2\&.2) Assign a specified scale value to output bands\&. If no scale is needed, it it recommended to set the value to 1\&. Scale and Offset are generally used together\&. For example, scale and offset might be used to store elevations in a unsigned 16bit integer file with a precision of 0\&.1, and starting from -100\&. True values would be calculated as: true_value = (pixel_value * scale) + offset Note: these values can be applied using -unscale during a gdal_translate run\&.
.PP
.IP "\fB\fB-offset\fP \fIvalue\fP:\fP" 1c
(GDAL >= 2\&.2) Assign a specified offset value to output bands\&. If no offset is needed, it recommended to set the value to 0\&. For more see scale\&.
.PP
.IP "\fB\fB-gcp\fP \fIpixel line easting northing [elevation]\fP:\fP" 1c
Add the indicated ground control point to the dataset\&. This option may be provided multiple times to provide a set of GCPs\&. 
.PP
.IP "\fB\fB-unsetmd\fP:\fP" 1c
(GDAL >= 2\&.0) Remove existing metadata (in the default metadata domain)\&. Can be combined with -mo\&.
.PP
.IP "\fB\fB-mo\fP \fI'META-TAG=VALUE'\fP:\fP" 1c
Passes a metadata key and value to set on the output dataset if possible\&. This metadata is added to the existing metadata items, unless -unsetmd is also specified\&.
.PP
.IP "\fB\fB-oo\fP \fI'NAME=VALUE'\fP:\fP" 1c
(GDAL >= 2\&.0) Open option (format specific)\&.
.PP
.PP
.PP
-a_ullr, -tr and -unsetgt options are exclusive\&.
.PP
-unsetstats and either -stats or -approx_stats options are exclusive\&.
.SH "EXAMPLE"
.PP
.PP
.nf
gdal_edit -mo DATUM=WGS84 -mo PROJ=GEODETIC -a_ullr 7 47 8 46 test.ecw
.fi
.PP
.SH "AUTHORS"
.PP
Even Rouault <even dot rouault at mines dash paris dot org> 
